### ISSUE TITLE
bug fixes

### ISSUE THREAD

**Issue by PartapSBimrah** [sajorahasan/OkCredit-Clone#1]
You can see the screenshot I got an error in this code. please let me know.

![Screenshot (118)](https://user-images.githubusercontent.com/39325207/77327401-33591780-6d41-11ea-8ccf-1ecbb63e8015.png)

**Comment by sajorahasan** [comment]
Please clean and rebuild your project

**Comment by PartapSBimrah** [comment]
I have done this process 2-3 times but still got this error. See the screenshot and let me know which package I need to import but if we these following packages then we got `BASE_URL` not found.
![Screenshot (119)](https://user-images.githubusercontent.com/39325207/77386940-17da2500-6db2-11ea-9c61-0465da02a9a4.png)

**Comment by sajorahasan** [comment]
You must be importing the wrong BuildConfig import. You need import of your app package name and It will be only available if your build finish successfully, so try commenting both import statement & BuildConfig.BaseURL and then uncomment try again to import your package name BuildConfig after a successful build.
